export enum ActionType {
    GET_NOTES = "GET_NOTES",
    GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS",
    GET_NOTES_FAIL = "GET_NOTES_FAIL",
    POST_NOTES = "POST_NOTES",
    DEPOSIT = "deposit",
    WITHDRAW = "withdraw",
    BANKRUPT = "bankrupt",
    GET_USER_REQUEST = "GET_USER_REQUEST",
    GET_USER_SUCCESS = "GET_USER_SUCCESS",
    GET_USER_FAIL = "GET_USER_FAIL",
    GET_LOG_OUT = "GET_LOG_OUT",
    GET_PRODUCT_LIST ="GET_PRODUCT_LIST",
    GET_PRODUCT_LIST_SUCCESS ="GET_PRODUCT_LIST_SUCCESS",
    GET_PRODUCT_LIST_FAIL ="GET_PRODUCT_LIST_FAIL"
}
