export enum ActionType {
    GET_USER_REQUEST = "GET_USER_REQUEST",
    GET_USER_SUCCESS = "GET_USER_SUCCESS",
    GET_USER_FAIL = "GET_USER_FAIL",
    GET_LOG_OUT = "GET_LOG_OUT",
    GET_PRODUCT_LIST ="GET_PRODUCT_LIST",
    GET_PRODUCT_LIST_SUCCESS ="GET_PRODUCT_LIST_SUCCESS",
    GET_PRODUCT_LIST_FAIL ="GET_PRODUCT_LIST_FAIL",
    GET_CATEGORIES = "GET_CATEGORIES",
    GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
}
